// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBEI5LEOsVGx3-qtSvYMIJA9EvxVRd85s',
    appId: '1:835502822749:web:560389f16ea9822a2b04b4',
    messagingSenderId: '835502822749',
    projectId: 'road-aware-w26',
    authDomain: 'road-aware-w26.firebaseapp.com',
    storageBucket: 'road-aware-w26.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2NXgVyflj_9dthfIIZIhn64mWypfPOyI',
    appId: '1:835502822749:android:51363711d28fc8842b04b4',
    messagingSenderId: '835502822749',
    projectId: 'road-aware-w26',
    storageBucket: 'road-aware-w26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-u6pu46JqcRmJe32mBZCbQvTGZZ3Xi2o',
    appId: '1:835502822749:ios:7b4677126f6be32b2b04b4',
    messagingSenderId: '835502822749',
    projectId: 'road-aware-w26',
    storageBucket: 'road-aware-w26.firebasestorage.app',
    iosBundleId: 'com.example.roadAware',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-u6pu46JqcRmJe32mBZCbQvTGZZ3Xi2o',
    appId: '1:835502822749:ios:7b4677126f6be32b2b04b4',
    messagingSenderId: '835502822749',
    projectId: 'road-aware-w26',
    storageBucket: 'road-aware-w26.firebasestorage.app',
    iosBundleId: 'com.example.roadAware',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBEI5LEOsVGx3-qtSvYMIJA9EvxVRd85s',
    appId: '1:835502822749:web:eadd138927cfd98a2b04b4',
    messagingSenderId: '835502822749',
    projectId: 'road-aware-w26',
    authDomain: 'road-aware-w26.firebaseapp.com',
    storageBucket: 'road-aware-w26.firebasestorage.app',
  );
}
